language: cpp
os: osx
osx_image: xcode13.1
git:
  submodules: false
addons:
  ssh_known_hosts:
  - github.com
#  homebrew: all pre-installed by the osx_image
#    packages:
#    - freetype
#    - libevent
#    - libx11
#    - sqlite
#    - zlib

before_install:
- git submodule update --init
- curl --retry 5 --connect-timeout 30 --location https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-macosx.tar.gz | tar zfx -

- curl --retry 5 --connect-timeout 30 --location https://www.lua.org/ftp/lua-5.4.3.tar.gz | tar zfx -
- mv lua-5.4.3 lua
- cp premake/lua/premake5.lua lua/

- curl --retry 5 --connect-timeout 30 --location https://www.ambiera.at/downloads/irrKlang-64bit-1.6.0.zip | tar zfx -
- mv irrKlang-64bit-1.6.0 irrklang

- curl --retry 5 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.5.zip
- unzip -q irrlicht-1.8.5.zip
- mv irrlicht-1.8.5 irrlicht
- cd irrlicht/
- dos2unix ../premake/irrlicht/irrlicht.patch
- dos2unix include/IOSOperator.h
- dos2unix include/irrString.h
- dos2unix include/irrTypes.h
- dos2unix source/Irrlicht/CGUIEditBox.cpp
- dos2unix source/Irrlicht/CGUIListBox.cpp
- dos2unix source/Irrlicht/CIrrDeviceLinux.cpp
- dos2unix source/Irrlicht/CIrrDeviceWin32.cpp
- dos2unix source/Irrlicht/COSOperator.cpp
- dos2unix source/Irrlicht/COSOperator.h
- dos2unix source/Irrlicht/MacOSX/AppDelegate.h
- dos2unix source/Irrlicht/MacOSX/AppDelegate.mm
- dos2unix source/Irrlicht/MacOSX/CIrrDeviceMacOSX.h
- dos2unix source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm
- dos2unix source/Irrlicht/MacOSX/OSXClipboard.h
- dos2unix source/Irrlicht/MacOSX/OSXClipboard.mm
- patch -p1 < ../premake/irrlicht/irrlicht.patch
- cd ..

- ./premake5 gmake --cc=clang

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj
- cd ../../../../
- cd build
- make config=release -j$(nproc)

branches:
  only:
  - test
