language: cpp
os: osx
osx_image: xcode13.1
git:
  submodules: false
addons:
  ssh_known_hosts:
  - github.com
  homebrew:
    packages:
    - gpatch
    - unix2dos
#    - freetype # all pre-installed by the osx_image
#    - libevent
#    - libx11
#    - sqlite
#    - zlib

before_install:
- git submodule update --init
- curl --retry 5 --connect-timeout 30 --location https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz | tar zfx -
- chmod +x ./premake5

- curl --retry 5 --connect-timeout 30 --location https://www.lua.org/ftp/lua-5.4.4.tar.gz | tar zfx -
- mv lua-5.4.4 lua
- cp premake/lua/premake5.lua lua/

- curl --retry 5 --connect-timeout 30 --location https://www.ambiera.at/downloads/irrKlang-64bit-1.6.0.zip | tar zfx -
- mv irrKlang-64bit-1.6.0 irrklang

- curl --retry 5 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.5.zip
- unzip -q irrlicht-1.8.5.zip
- mv irrlicht-1.8.5 irrlicht
- cd irrlicht
- unix2dos ../premake/irrlicht/irrlicht.patch
- unix2dos source/Irrlicht/MacOSX/MacOSX.xcodeproj/project.pbxproj
- patch --binary -p1 < ../premake/irrlicht/irrlicht.patch
- cp -r include /usr/local/include/irrlicht
- cd ..

- ./premake5 gmake --cc=clang

script:
- cd irrlicht/source/Irrlicht/MacOSX
- xcodebuild -project MacOSX.xcodeproj
- cp build/Release/libIrrlicht.a /usr/local/lib/
- cd ../../../../
- cd build
- make config=release -j$(nproc)

branches:
  only:
  - test
